const DEFAULT_COLS = 3;
const DEFAULT_ELEMENT_MIN_WIDTH = 420;
const DEFAULT_GAP = 32;

const COL_KEY_PREFIX = 'masonry-col-';
const CELL_KEY_PREFIX = 'masonry-cell-';

export { DEFAULT_COLS, DEFAULT_ELEMENT_MIN_WIDTH, DEFAULT_GAP, COL_KEY_PREFIX, CELL_KEY_PREFIX };
